import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyLedger, applyCommand, money, meterAmount, sum, addMonths, monthlySegments, leaseBills, date, billTotals, cashSummary, yuan } from '../lib/ledger.ts';
function fixture(options={}) {let s=emptyLedger();const run=c=>(s=applyCommand(s,c));run({type:'property.save',name:'测试房源',source:'leased',rooms:'A房\nB房'});run({type:'tenant.save',name:'测试租客'});const propertyId=s.properties[0].id,tenantId=s.tenants[0].id;run({type:'lease.create',side:'in',unit:'A房',propertyId,tenantId,start:'2025-01-01',end:'2025-03-31',rent:'3000',deposit:'3000',cycle:'3',advance:'0',fees:[],...options});return {get state(){return s;},run,propertyId,tenantId,get rent(){return s.bills.find(b=>b.category==='rent');},get deposit(){return s.bills.find(b=>b.category==='deposit');}};}
function pay(f,billId,amount,extra={}) {f.run({type:'entry.create',billId,kind:'payment',amount,date:'2025-01-01',method:'微信',...extra});}
test('currency is exact integer fen; invalid inputs fail',()=>{assert.equal(sum([money('0.10'),money('0.20')]),30);assert.equal(yuan(10001),'100.01');for(const x of ['1e3','-1','1.001','NaN','1,000','',' 2'])assert.throws(()=>money(x));assert.equal(money('0'),0);});
test('meter calculation retains precision and rounds half up once',()=>{assert.equal(meterAmount('100','101','0.555'),56);assert.equal(meterAmount('123.001','145.456','0.5823'),1308);assert.equal(meterAmount('0','0.001','5'),1);assert.throws(()=>meterAmount('9','8','1'));assert.throws(()=>meterAmount('0','1','0.12345'));});
test('dates are real dates; month-end anchored without drift',()=>{assert.throws(()=>date('2025-02-29'));assert.equal(date('2024-02-29'),'2024-02-29');assert.equal(addMonths('2024-01-31',1),'2024-02-29');assert.equal(addMonths('2024-01-31',2),'2024-03-31');const rows=monthlySegments('2025-01-31','2025-03-30',300000);assert.deepEqual(rows.map(r=>r.amount),[300000,300000]);assert.deepEqual(rows.map(r=>r.end),['2025-02-27','2025-03-30']);});
test('partial month and quarterly grouping agree',()=>{const f=fixture({start:'2025-01-01',end:'2025-02-14',rent:'3100'});assert.equal(f.rent.amount,465000);assert.equal(f.rent.start,'2025-01-01');assert.equal(f.rent.end,'2025-02-14');assert.equal(leaseBills(f.state.leases[0]).length,2);});
test('deposit receive → partial rent → apply → refund remains balanced',()=>{const f=fixture();pay(f,f.deposit.id,'3000');pay(f,f.rent.id,'6000');f.run({type:'entry.create',kind:'apply',billId:f.rent.id,depositId:f.deposit.id,amount:'1000',date:'2025-01-02'});f.run({type:'entry.create',kind:'refund',billId:f.deposit.id,amount:'2000',date:'2025-01-03'});assert.equal(billTotals(f.state,f.deposit.id).balance,0);assert.equal(billTotals(f.state,f.rent.id).remaining,200000);const c=cashSummary(f.state);assert.equal(c.operatingIn,700000);assert.equal(c.cashNet,700000);assert.equal(c.cashNet-c.operatingNet,0);assert.throws(()=>pay(f,f.rent.id,'2000.01'));});
test('upper landlord deposit is an asset, repair is operating outflow',()=>{const f=fixture();f.run({type:'lease.create',propertyId:f.propertyId,side:'out',unit:'整套',landlord:'一手房东',start:'2025-01-01',end:'2025-12-31',rent:'1000',deposit:'2000',cycle:'1',advance:'0',fees:[]});const d=f.state.bills.find(b=>b.side==='out'&&b.category==='deposit');pay(f,d.id,'2000');f.run({type:'bill.create',propertyId:f.propertyId,unit:'A房',side:'out',category:'repair',title:'更换水龙头',amount:'150.25',due:'2025-01-02'});pay(f,f.state.bills.at(-1).id,'150.25');assert.equal(cashSummary(f.state).cashNet,-215025);assert.equal(cashSummary(f.state).operatingOut,15025);f.run({type:'entry.create',kind:'refund',billId:d.id,amount:'1000',date:'2025-01-03'});assert.equal(billTotals(f.state,d.id).balance,100000);assert.equal(cashSummary(f.state).cashNet,-115025);});
test('refund and reversal cannot spend unavailable deposit',()=>{const f=fixture();pay(f,f.deposit.id,'3000');const original=f.state.entries[0].id;f.run({type:'entry.create',kind:'apply',billId:f.rent.id,depositId:f.deposit.id,amount:'1000',date:'2025-01-02'});assert.throws(()=>f.run({type:'entry.create',kind:'refund',billId:f.deposit.id,amount:'2000.01',date:'2025-01-02'}));assert.throws(()=>f.run({type:'entry.reverse',id:original,date:'2025-01-03',note:'错误收押'}));const applied=f.state.entries.at(-1).id;f.run({type:'entry.reverse',id:applied,date:'2025-01-03',note:'错误抵扣'});f.run({type:'entry.reverse',id:original,date:'2025-01-03',note:'错误收押'});assert.equal(cashSummary(f.state).cashNet,0);assert.equal(billTotals(f.state,f.rent.id).remaining,900000);assert.throws(()=>f.run({type:'entry.reverse',id:applied,date:'2025-01-04',note:'重复'}));});
test('overlap prevention includes whole versus rooms, allows independent rooms and next-day renewal',()=>{const f=fixture();const c={type:'lease.create',propertyId:f.propertyId,tenantId:f.tenantId,side:'in',unit:'整套',start:'2025-02-01',end:'2025-06-30',rent:'1000',deposit:'0',cycle:'1',advance:'0'};assert.throws(()=>f.run(c));f.run({...c,unit:'B房'});f.run({...c,unit:'A房',start:'2025-04-01'});assert.equal(f.state.leases.length,3);});
test('cross-contract deposit application rejected without mutation',()=>{const f=fixture();pay(f,f.deposit.id,'3000');f.run({type:'lease.create',propertyId:f.propertyId,tenantId:f.tenantId,side:'in',unit:'B房',start:'2025-01-01',end:'2025-03-31',rent:'1000',deposit:'0',cycle:'1',advance:'0'});const before=JSON.stringify(f.state);assert.throws(()=>f.run({type:'entry.create',kind:'apply',billId:f.state.bills.at(-1).id,depositId:f.deposit.id,amount:'1000',date:'2025-01-02'}));assert.equal(JSON.stringify(f.state),before);});
test('idempotent request is applied once',()=>{const s=emptyLedger(),c={type:'property.save',name:'幂等测试',source:'owned',rooms:''};const next=applyCommand(s,c,'request-12345678');assert.equal(applyCommand(next,c,'request-12345678'),next);assert.equal(next.properties.length,1);});
test('tenant self-paid fees and fixed automatic fees cannot be duplicated',()=>{const f=fixture({fees:[{category:'water',mode:'self',amount:'0',rate:'0'},{category:'internet',mode:'fixed',amount:'30',rate:'0'}]});assert.equal(f.state.bills.filter(b=>b.category==='internet').length,3);assert.throws(()=>f.run({type:'bill.create',propertyId:f.propertyId,leaseId:f.state.leases[0].id,side:'in',category:'water',amount:'10',due:'2025-01-31'}));assert.throws(()=>f.run({type:'bill.create',propertyId:f.propertyId,leaseId:f.state.leases[0].id,side:'in',category:'internet',amount:'30',due:'2025-01-31'}));});
test('early termination requires refund first, then prorates and keeps deposit',()=>{const f=fixture({rent:'3100'});pay(f,f.rent.id,'9300');assert.throws(()=>f.run({type:'lease.close',id:f.state.leases[0].id,end:'2025-02-14',note:'退租'}));f.run({type:'entry.create',billId:f.rent.id,kind:'refund',amount:'4650',date:'2025-02-14'});f.run({type:'lease.close',id:f.state.leases[0].id,end:'2025-02-14',note:'退租'});assert.equal(f.rent.amount,465000);assert.equal(billTotals(f.state,f.rent.id).remaining,0);assert.equal(f.deposit.amount,300000);});
test('adjustments below settlement rejected; voiding preserves cash audit',()=>{const f=fixture();pay(f,f.rent.id,'100');assert.throws(()=>f.run({type:'bill.adjust',id:f.rent.id,amount:'99.99',due:'2025-01-01',note:'减免'}));assert.throws(()=>f.run({type:'bill.void',id:f.rent.id,note:'误录'}));f.run({type:'entry.create',billId:f.rent.id,kind:'refund',amount:'100',date:'2025-01-02'});f.run({type:'bill.void',id:f.rent.id,note:'误录'});assert.equal(f.rent.voided,true);assert.equal(cashSummary(f.state).cashNet,0);});
test('refunds and deposit application cannot predate the money funding them',()=>{const f=fixture();pay(f,f.deposit.id,'3000',{date:'2025-01-10'});assert.throws(()=>f.run({type:'entry.create',billId:f.deposit.id,kind:'refund',amount:'100',date:'2025-01-09'}));assert.throws(()=>f.run({type:'entry.create',billId:f.rent.id,depositId:f.deposit.id,kind:'apply',amount:'100',date:'2025-01-09'}));pay(f,f.rent.id,'100',{date:'2025-01-10'});assert.throws(()=>f.run({type:'entry.create',billId:f.rent.id,kind:'refund',amount:'100',date:'2025-01-09'}));});
test('monthly reversal report uses reversal date, not original date',()=>{const f=fixture();pay(f,f.rent.id,'100');f.run({type:'entry.reverse',id:f.state.entries[0].id,date:'2025-02-01',note:'发现录错'});assert.equal(cashSummary(f.state,'2025-01-01','2025-01-31').operatingIn,10000);assert.equal(cashSummary(f.state,'2025-02-01','2025-02-28').operatingIn,-10000);});
test('metered bills preserve formula and prevent overlapping fee periods',()=>{const f=fixture({fees:[{category:'electricity',mode:'metered',amount:'0',rate:'0.555'}]});const c={type:'bill.create',propertyId:f.propertyId,leaseId:f.state.leases[0].id,side:'in',category:'electricity',metered:true,previous:'10',current:'11',rate:'0.555',due:'2025-02-01',start:'2025-01-01',end:'2025-01-31'};f.run(c);assert.equal(f.state.bills.at(-1).amount,56);assert.match(f.state.bills.at(-1).note,/10 → 11/);assert.throws(()=>f.run(c));});
test('cash equals operating net plus held tenant deposits minus upper deposits',()=>{const f=fixture();pay(f,f.rent.id,'1234.56');pay(f,f.deposit.id,'789.01');const c=cashSummary(f.state);assert.equal(c.cashNet,c.operatingNet+billTotals(f.state,f.deposit.id).balance);});
test('refund is a cash outflow; upper-landlord refund is a cash inflow',()=>{const f=fixture();pay(f,f.deposit.id,'3000');f.run({type:'entry.create',billId:f.deposit.id,kind:'refund',amount:'2000',date:'2025-01-02'});assert.equal(cashSummary(f.state).cashIn,300000);assert.equal(cashSummary(f.state).cashOut,200000);assert.equal(cashSummary(f.state).cashNet,100000);f.run({type:'bill.create',propertyId:f.propertyId,side:'out',category:'repair',amount:'100',due:'2025-01-01'});const b=f.state.bills.at(-1);pay(f,b.id,'100');f.run({type:'entry.create',billId:b.id,kind:'refund',amount:'30',date:'2025-01-03'});assert.equal(cashSummary(f.state).cashIn,303000);assert.equal(cashSummary(f.state).cashOut,210000);assert.equal(cashSummary(f.state).operatingOut,7000);});
