import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyLedger,applyCommand,billTotals,leaseBills } from '../lib/ledger.ts';
import { currentBillIds,upcomingBills,entryView,filterEntries,entrySummary,costSummary,billExplanation } from '../lib/reporting.ts';
function fixture(){let s=emptyLedger();const run=(c,key)=>s=applyCommand(s,c,key);run({type:'property.save',name:'房源甲',source:'leased',rooms:'A房\nB房'});run({type:'tenant.save',name:'租客甲'});const p=s.properties[0].id,t=s.tenants[0].id;run({type:'lease.create',propertyId:p,tenantId:t,unit:'A房',side:'in',start:'2026-09-08',end:'2027-09-08',rent:'1600',deposit:'1600',cycle:'1',advance:'3',fees:[{category:'water',mode:'fixed',amount:'30',rate:'0'}]});return {get s(){return s;},run,p,t};}
test('default queue keeps all overdue and only next future period per charge',()=>{const f=fixture(),ids=currentBillIds(f.s,'2026-09-08');assert.equal(ids.size,5);assert.ok(![...ids].some(id=>id.endsWith('2027-09-08')));assert.equal(f.s.bills.filter(b=>ids.has(b.id)&&b.category==='water').length,2);assert.equal(f.s.bills.filter(b=>ids.has(b.id)&&b.category==='rent').length,2);});
test('after next period is settled, queue advances and reminder excludes it',()=>{const f=fixture(),next=f.s.bills.find(b=>b.category==='rent'&&b.start==='2026-10-08');f.run({type:'entry.create',billId:next.id,kind:'payment',amount:'1600',date:'2026-09-08'});const ids=currentBillIds(f.s,'2026-09-08');assert.ok(!ids.has(next.id));assert.ok([...ids].some(id=>id.endsWith(':rent:2026-11-08')));assert.ok(!upcomingBills(f.s,'2026-10-01',7).some(b=>b.id===next.id));});
test('upcoming reminders use due date, both directions and exact horizon',()=>{const f=fixture();f.run({type:'bill.create',propertyId:f.p,side:'out',category:'repair',amount:'100',due:'2026-09-15'});const bills=upcomingBills(f.s,'2026-09-08',7);assert.equal(bills.length,1);assert.equal(bills[0].side,'out');assert.equal(upcomingBills(f.s,'2026-09-08',6).length,0);});
test('one-day final water bill is a documented inclusive-end proration, not duplicate water',()=>{const f=fixture(),b=f.s.bills.find(b=>b.category==='water'&&b.start==='2027-09-08');assert.equal(b.amount,100);assert.equal(b.due,'2027-09-05');assert.match(billExplanation(f.s,b),/共 1 天/);assert.match(billExplanation(f.s,b),/¥ 30.00/);assert.match(billExplanation(f.s,b),/¥ 1.00/);const annual=leaseBills({...f.s.leases[0],end:'2027-09-07'});assert.equal(annual.filter(x=>x.category==='water').length,12);assert.ok(!annual.some(x=>x.start==='2027-09-08'));});
test('one-step cost recording is atomic, exact and retry idempotent',()=>{const f=fixture(),command={type:'expense.create',propertyId:f.p,unit:'A房',category:'decoration',title:'装修',amount:'123.45',date:'2026-09-08',method:'银行转账'};const before=JSON.stringify(f.s);assert.throws(()=>f.run({...command,date:'2099-01-01'}));assert.equal(JSON.stringify(f.s),before);f.run(command,'expense-request-123');const b=f.s.bills.at(-1);assert.equal(billTotals(f.s,b.id).remaining,0);assert.equal(f.s.entries.at(-1).amount,12345);const size=f.s.entries.length;f.run(command,'expense-request-123');assert.equal(f.s.entries.length,size);assert.equal(costSummary(f.s).netInvestment,12345);});
test('cost combines upper rent, deposits, renovation and fees without counting tenant receipts',()=>{const f=fixture();for(const category of ['rent','repair','decoration','other'])f.run({type:'expense.create',propertyId:f.p,category,title:category,amount:'100',date:'2026-09-08'});f.run({type:'lease.create',propertyId:f.p,side:'out',unit:'整套',landlord:'上游',start:'2026-09-08',end:'2027-09-07',rent:'1000',deposit:'2000',cycle:'1',advance:'0'});const dep=f.s.bills.find(b=>b.side==='out'&&b.category==='deposit');f.run({type:'entry.create',billId:dep.id,kind:'payment',amount:'2000',date:'2026-09-08'});const c=costSummary(f.s);assert.equal(c.netInvestment,240000);assert.equal(c.consumed,40000);assert.equal(c.heldDeposit,200000);assert.equal(filterEntries(f.s,{costOnly:true}).length,5);});
test('flow filters follow real cash direction, including refunds and signed corrections',()=>{const f=fixture();f.run({type:'expense.create',propertyId:f.p,unit:'A房',category:'repair',title:'热水器',amount:'100',date:'2026-09-08'});const bill=f.s.bills.at(-1),paid=f.s.entries.at(-1);f.run({type:'entry.create',billId:bill.id,kind:'refund',amount:'30',date:'2026-09-08'});assert.equal(filterEntries(f.s,{direction:'out'}).length,1);assert.equal(filterEntries(f.s,{direction:'in',category:'repair',propertyId:f.p,query:'热水器'}).length,1);assert.equal(entrySummary(f.s,f.s.entries).received,3000);assert.equal(costSummary(f.s).netInvestment,7000);f.run({type:'entry.reverse',id:f.s.entries.at(-1).id,date:'2026-09-08',note:'退款误录'});assert.equal(entryView(f.s,f.s.entries.at(-1)).signedAmount,-3000);assert.equal(entrySummary(f.s,filterEntries(f.s,{direction:'in'})).received,0);assert.equal(filterEntries(f.s,{start:'2026-09-09'}).length,0);assert.equal(filterEntries(f.s,{unit:'B房'}).length,0);assert.equal(entryView(f.s,paid).direction,'out');});
