'use client';
import { createContext, useContext } from 'react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { categories, parseLease, leaseBills, formatMoney, sum, meterAmount, yuan, type Ledger, type Command } from '@/lib/ledger';
export type Draft = Record<string,string>;
export const utilities = ['water','electricity','internet','propertyFee'] as const;
export const modeLabels = { self:'租客自行缴纳',manual:'按账单金额代收',metered:'按表数计算代收',fixed:'固定月费代收' };
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}) { return <label className="field"><span>{label}</span><Select value={value} onValueChange={v=>onChange(v??'')} items={Object.fromEntries(options)}><SelectTrigger className="form-select" aria-label={label}><SelectValue placeholder="请选择"/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label>; }
export function Field({label,name,d,set,type='text',required=false,placeholder='',wide=false}:{label:string;name:string;d:Draft;set:(key:string,v:string)=>void;type?:string;required?:boolean;placeholder?:string;wide?:boolean}) {return <label className={'field '+(wide?'wide':'')}><span>{label}{required&&<em> *</em>}</span>{type==='textarea'?<Textarea value={d[name]??''} onChange={e=>set(name,e.target.value)} required={required} maxLength={1000} placeholder={placeholder}/>:<Input value={d[name]??''} onChange={e=>set(name,e.target.value)} type={type==='money'?'text':type} inputMode={type==='money'?'decimal':undefined} required={required} placeholder={placeholder} maxLength={type==='date'?undefined:300}/>}</label>; }
export function toCommand(type:string,d:Draft):Command {if(type==='lease.create')return {...d,type,unit:d.side==='out'?'整套':d.unit,fees:d.side==='out'?[]:utilities.map(category=>({category,mode:d[category+'_mode']??'self',amount:d[category+'_amount']??'0',rate:d[category+'_rate']??'0'}))};return {...d,type,metered:d.metered==='yes'};}
const FormContext=createContext<{d:Draft;set:(key:string,v:string)=>void}>({d:{},set:()=>{}});
function F(p:Omit<React.ComponentProps<typeof Field>,'d'|'set'>) {const {d,set}=useContext(FormContext);return <Field {...p} d={d} set={set}/>;}
function C({name,label,options}:{name:string;label:string;options:[string,string][]}) {const {d,set}=useContext(FormContext);return <Choice label={label} value={d[name]??''} onChange={v=>set(name,v)} options={options}/>;}
type EditorProps={type:string;d:Draft;set:(key:string,v:string)=>void;s:Ledger};
export function EditorFields(props:EditorProps) {return <FormContext.Provider value={{d:props.d,set:props.set}}><EditorBody {...props}/></FormContext.Provider>;}
function EditorBody({type,d,set,s}:EditorProps) {
 const property=s.properties.find(p=>p.id===d.propertyId);
 const propertyOptions:[string,string][]=[['','选择房源'],...s.properties.filter(p=>!p.archived).map(p=>[p.id,p.name] as [string,string])];
 const unitOptions:[string,string][]=['整套',...(property?.rooms??[])].map(r=>[r,r==='整套'?'整套出租':r]);
 const lease=s.leases.find(l=>l.id===d.leaseId);
 if(type==='property.save')return <div className="form-grid"><F label="房源名称" name="name" required placeholder="例如：万科城 3 栋 1201" wide/><F label="详细地址" name="address" wide/><C label="房源来源" name="source" options={[["owned","自有房源"],["leased","从一手房东租入"]]}/><F label="分租房间（可选）" name="rooms" type="textarea" wide placeholder="每行一个房间名，例如 A房、B房；整租无需填写"/><F label="房源备注" name="note" type="textarea" wide/><p className="form-hint wide">同一房源支持整套或分房间签约；系统会检查租期是否重叠。</p></div>;
 if(type==='tenant.save')return <div className="form-grid"><F label="租客姓名" name="name" required/><F label="联系电话" name="phone" type="tel"/><F label="备注" name="note" type="textarea" wide/></div>;
 if(type==='lease.create') {let preview:ReturnType<typeof leaseBills>=[],previewError='';try {preview=leaseBills(parseLease(s,toCommand(type,d),'preview'));}catch(e){previewError=e instanceof Error?e.message:'请完善合同';}
 return <><div className="form-grid"><C label="合同类型" name="side" options={[["in","出租给租客（应收）"],["out","从一手房东租入（应付）"]]}/><Choice label="房源" value={d.propertyId??''} onChange={v=>{set('propertyId',v);set('unit','整套');}} options={propertyOptions}/>{d.side==='out'?<><F label="一手房东姓名" name="landlord" required/><F label="房东电话" name="phone" type="tel"/></>:<><C label="房间" name="unit" options={unitOptions}/><C label="租客" name="tenantId" options={[["","选择已登记租客"],...s.tenants.map(t=>[t.id,t.name+(t.phone?' · '+t.phone:'')] as [string,string])]}/></>}<F label="起租日期" name="start" type="date" required/><F label="结束日期（含当天）" name="end" type="date" required/><F label="月租金（元）" name="rent" type="money" required/><F label="押金金额（元）" name="deposit" type="money" required/><C label="付款周期" name="cycle" options={[["1","每月付"],["2","每 2 个月付"],["3","每季度付"],["6","每半年付"],["12","每年付"]]}/><F label="每期提前几天付款" name="advance" type="number" required/><p className="form-hint wide">付款日＝每期起始日减提前天数；每期从起租日推算，月末自动对齐当月最后一天。租金不足一个租约月按实际天数折算。</p></div>{d.side==='in'&&<section className="form-section"><h3>水电及其他费用</h3>{utilities.map(k=><div className="fee-rule" key={k}><Choice label={categories[k]} value={d[k+'_mode']??'self'} onChange={v=>set(k+'_mode',v)} options={Object.entries(modeLabels).filter(([m])=>m!=='metered'||k==='water'||k==='electricity') as [string,string][]}/>{d[k+'_mode']==='fixed'&&<F label="每月金额（元）" name={k+'_amount'} type="money" required/>}{d[k+'_mode']==='metered'&&<F label={'单价（元 / '+(k==='water'?'立方米':'度')+'）'} name={k+'_rate'} type="money" required/>}</div>)}<p className="form-hint">固定费用每月生成账单，尾月按天折算；按表或按账单代收的费用，在“新增账单”中录入。自行缴纳的费用不会出账。</p></section>}<F label="合同备注" name="note" type="textarea" wide/><section className="preview-panel"><h3>签约前核对账单</h3>{previewError?<p className="form-hint">{previewError}</p>:<><p>租金合计 <b>{formatMoney(sum(preview.filter(b=>b.category==='rent').map(b=>b.amount)))}</b> · 押金 <b>{formatMoney(sum(preview.filter(b=>b.category==='deposit').map(b=>b.amount)))}</b> · 共 {preview.length} 笔</p><div className="preview-scroll"><Table><TableHeader><TableRow><TableHead>项目 / 期间</TableHead><TableHead>应付日期</TableHead><TableHead className="number">金额</TableHead></TableRow></TableHeader><TableBody>{preview.map(b=><TableRow key={b.id}><TableCell>{b.title}<small>{b.start} 至 {b.end}</small></TableCell><TableCell>{b.due}</TableCell><TableCell className="number">{formatMoney(b.amount)}</TableCell></TableRow>)}</TableBody></Table></div></>}</section></>; }
 if(type==='bill.create'){let calculated='';if(d.metered==='yes')try{calculated=yuan(meterAmount(d.previous,d.current,d.rate));}catch{calculated='请填写有效表数与单价';}
 return <div className="form-grid"><Choice label="房源" value={d.propertyId??''} onChange={v=>{set('propertyId',v);set('leaseId','');set('unit','整套');}} options={propertyOptions}/><Choice label="关联合同" value={d.leaseId??''} onChange={v=>{set('leaseId',v);const l=s.leases.find(l=>l.id===v);if(l){set('side',l.side);set('unit',l.unit);const f=l.fees.find(f=>f.category===d.category);if(f?.mode==='metered'){set('metered','yes');set('rate',f.rate);}else set('metered','no');}}} options={[["","不关联合同（房源成本等）"],...s.leases.filter(l=>l.propertyId===d.propertyId).map(l=>[l.id,(l.side==='in'?(s.tenants.find(t=>t.id===l.tenantId)?.name??'租客'):l.landlord)+' · '+l.unit+' · '+l.start] as [string,string])]}/>{!lease&&<><C label="房间 / 成本归属" name="unit" options={unitOptions}/><C label="收支方向" name="side" options={[["in","应收"],["out","应付 / 成本支出"]]}/></>}<Choice label="费用类别" value={d.category??'repair'} onChange={v=>{set('category',v);const f=lease?.fees.find(f=>f.category===v);set('metered',f?.mode==='metered'?'yes':'no');if(f?.rate)set('rate',f.rate);}} options={Object.entries(categories).filter(([k])=>k!=='deposit'&&(!lease||k!=='rent')) as [string,string][]}/><F label="费用说明" name="title" placeholder="例如：更换厨房水龙头"/>{['water','electricity'].includes(d.category)&&<C label="计算方式" name="metered" options={[["no","直接填写金额"],["yes","按表数 × 单价"]]}/>} {d.metered==='yes'?<><F label="上期表数（最多 3 位小数）" name="previous" type="money" required/><F label="本期表数（最多 3 位小数）" name="current" type="money" required/><F label="单价（最多 4 位小数）" name="rate" type="money" required/><div className="calculated"><span>计算金额（元）</span><b>{calculated}</b></div></>:<F label="金额（元）" name="amount" type="money" required/>}<F label="应收 / 应付日期" name="due" type="date" required/><F label="费用期间开始" name="start" type="date" required/><F label="费用期间结束" name="end" type="date" required/><F label="备注 / 分摊依据" name="note" type="textarea" wide placeholder="如有分摊，填写总金额、分摊人数及本房间承担金额"/>{lease&&<p className="form-hint wide">关联合同：{lease.unit}，{lease.start} 至 {lease.end}。方向为{lease.side==='in'?'应收':'应付'}。已设为自行缴纳或固定月费的项目不能重复出账。</p>}<p className="form-hint wide">这里只创建应收或应付。实际收到或付出钱后，再进入账单登记收付款。</p></div>;}
 if(type==='entry.create')return <div className="form-grid"><F label={d.kind==='apply'?'抵扣金额（元）':d.kind==='refund'?'退款金额（元）':'本次实际收付（元）'} name="amount" type="money" required/><F label="实际发生日期" name="date" type="date" required/>{d.kind!=='apply'&&<C label="收付方式" name="method" options={[["微信","微信"],["支付宝","支付宝"],["银行转账","银行转账"],["现金","现金"],["其他","其他"]]}/>}<F label="备注" name="note" type="textarea" wide/>{d.kind==='apply'&&<p className="form-hint wide">使用同一合同的押金结清此账单。押金余额减少、账单欠款减少，本次没有现金收付。</p>}</div>;
 if(type==='bill.adjust')return <div className="form-grid"><F label="调整后应收 / 应付总额（元）" name="amount" type="money" required/><F label="应收 / 应付日期" name="due" type="date" required/><F label="调整原因" name="note" type="textarea" required wide/><p className="form-hint wide">修改后的金额不能小于已结算金额。调整记录永久保留；调整后此账单改为手动管理，提前退租时需要单独核对。</p></div>;
 if(type==='lease.close')return <div className="form-grid"><F label="实际结束日期（含当天）" name="end" type="date" required/><F label="提前结束原因" name="note" type="textarea" required wide/><p className="form-hint wide">自动租金与固定费用按新租期重算。若已收金额超过新应收，需先办理退款。押金、手动新增或调整过的账单保留，需单独结算。</p></div>;
 if(type==='entry.reverse')return <div className="form-grid"><F label="冲销日期" name="date" type="date" required/><F label="冲销原因" name="note" type="textarea" required wide/><p className="form-hint wide">用于更正录错的流水。原记录保留，并新增一笔反向记录。实际发生退款时，请使用账单的“退款”操作。</p></div>;
 if(type==='bill.void')return <F label="作废原因" name="note" type="textarea" required wide/>;
 return null;
}
