'use client';
import { useState } from 'react';
import { Download, Plus, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Empty, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { categories, formatMoney, today, yuan, type Ledger, type Entry } from '@/lib/ledger';
import { costSummary, entrySummary, entryView, filterEntries } from '@/lib/reporting';
import { Choice } from './forms';

export function Transactions({s,propertyId,onReverse,costOnly=false,onAddCost}:{s:Ledger;propertyId:string;onReverse:(e:Entry)=>void;costOnly?:boolean;onAddCost?:()=>void}) {
 const [direction,setDirection]=useState('all'),[category,setCategory]=useState('all'),[unit,setUnit]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[query,setQuery]=useState(''),[limit,setLimit]=useState(50);
 const periodInvalid=!!from&&!!to&&from>to;
 const entries=periodInvalid?[]:filterEntries(s,{propertyId,unit,direction,category,start:from,end:to,query,costOnly});
 const summary=entrySummary(s,entries);const costs=costSummary(s,propertyId);
 const rooms=propertyId?s.properties.find(p=>p.id===propertyId)?.rooms??[]:[];
 const exportCsv=()=>{const rows=[['日期','房源','房间','收付方向','费用类别','费用说明','金额（元，冲销为负）','收付方式','备注','流水编号','冲销原编号'],...entries.map(e=>{const v=entryView(s,e),b=v.bill;return [e.date,s.properties.find(p=>p.id===b.propertyId)?.name??'',b.unit,v.label,categories[b.category],b.title,yuan(v.signedAmount),e.method,e.note,e.id,e.reversalOf];})];const content='\ufeff'+rows.map(r=>r.map(x=>'"'+(/^[=+\-@\t\r]/.test(x)?"'"+x:x).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=(costOnly?'成本流水-':'收付流水-')+today()+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <>{costOnly&&<><div className="cost-stat-grid"><section className="stat stat-primary"><div className="stat-label">累计净投入（含上游押金）</div><div className="stat-value">{formatMoney(costs.netInvestment)}</div><p>实际支出 {formatMoney(costs.invested)} − 收回 {formatMoney(costs.recovered)}</p></section><section className="stat"><div className="stat-label">其中：费用性支出</div><div className="stat-value">{formatMoney(costs.consumed)}</div><p>房租、装修、维修、杂费；按付款口径，未按租期分摊</p></section><section className="stat"><div className="stat-label">其中：可退上游押金</div><div className="stat-value">{formatMoney(costs.heldDeposit)}</div><p>资金占用，退回后减少净投入</p></section></div><p className="bottom-note">成本包括付给一手房东的房租、押金及房源装修、维修和杂费。退还租客押金属于退款支出，不属于房源成本。上方为当前房源累计数据，下方按条件查询。</p></>}
 <section className="panel"><div className="panel-title"><h2>{costOnly?'成本付款与收回':'收付款流水'}</h2><div className="heading-actions">{costOnly&&<Button className="primary-button" disabled={!s.properties.some(p=>!p.archived)} onClick={onAddCost}><Plus size={16}/>记录成本付款</Button>}<Button variant="outline" className="action-button" onClick={exportCsv} disabled={periodInvalid}><Download size={16}/>导出筛选结果</Button></div></div>
 <div className="transaction-filters"><Tabs value={direction} onValueChange={v=>{setDirection(String(v));setLimit(50);}}><TabsList className="filter-tabs">{[['all','全部'],['in','收款'],['out','付款'],['offset','押金抵扣']].map(([v,t])=><TabsTrigger key={v} value={v}>{t}</TabsTrigger>)}</TabsList></Tabs><div className="transaction-filter-grid"><Choice label="费用类别" value={category} onChange={v=>{setCategory(v);setLimit(50);}} options={[["all","全部费用"],...Object.entries(categories),["utilities","水电网物业及其他杂费"]] as [string,string][]}/><Choice label="房间" value={unit} onChange={v=>{setUnit(v);setLimit(50);}} options={[["","全部房间"],["整套","整套"],...rooms.map(r=>[r,r] as [string,string])]}/><label className="field"><span>开始日期</span><Input type="date" value={from} onChange={e=>{setFrom(e.target.value);setLimit(50);}}/></label><label className="field"><span>结束日期</span><Input type="date" value={to} onChange={e=>{setTo(e.target.value);setLimit(50);}}/></label><label className="field"><span>关键词</span><div className="search-field"><Search size={17}/><Input placeholder="房源 / 租客 / 备注" value={query} onChange={e=>{setQuery(e.target.value);setLimit(50);}}/></div></label></div></div>
 {periodInvalid?<div role="alert" className="error-banner">结束日期不能早于开始日期。</div>:<div className="table-summary">共 {entries.length} 笔 · 收款净额 {formatMoney(summary.received)} · 付款净额 {formatMoney(summary.paid)} · 押金抵扣 {formatMoney(summary.offset)}<br/>冲销以负数计入原收付方向；押金抵扣不产生现金收付。</div>}
 {entries.length?<><Table className="ledger-table"><TableHeader><TableRow><TableHead>日期 / 房源</TableHead><TableHead>收付方向</TableHead><TableHead>费用</TableHead><TableHead className="number">金额</TableHead><TableHead className="hide-small">备注 / 方式</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{entries.slice(-limit).reverse().map(e=>{const v=entryView(s,e),b=v.bill,reversed=s.entries.some(x=>x.reversalOf===e.id);return <TableRow key={e.id}><TableCell>{e.date}<small>{s.properties.find(p=>p.id===b.propertyId)?.name} · {b.unit}</small></TableCell><TableCell><span className={'status '+(v.direction==='in'?'green':v.direction==='out'?'amber':'blue')}>{v.label}</span>{reversed&&<small>已冲销</small>}</TableCell><TableCell>{categories[b.category]}<small>{b.title}</small></TableCell><TableCell className={'number '+(v.direction==='in'?'income':v.direction==='out'?'expense':'')}>{formatMoney(v.signedAmount)}</TableCell><TableCell className="hide-small wrap-cell">{e.note||'—'}<small>{e.method}</small></TableCell><TableCell>{e.kind!=='reversal'&&!reversed&&<Button variant="ghost" onClick={()=>onReverse(e)}>冲销</Button>}</TableCell></TableRow>;})}</TableBody></Table>{entries.length>limit&&<Button variant="ghost" className="more-button" onClick={()=>setLimit(limit+50)}>显示更多（{Math.min(limit,entries.length)} / {entries.length}）</Button>}</>:<Empty className="empty-block"><EmptyTitle>暂无符合条件的{costOnly?'成本':'收付'}流水</EmptyTitle><EmptyDescription>{costOnly?'可直接记录装修、维修和杂费付款；上游合同中的房租与押金付款也会自动归入这里。':'登记收付款后，可按收款、付款、费用、房源、房间及日期查询。'}</EmptyDescription></Empty>}
 </section></>;
}
