'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent, type CSSProperties } from 'react';
import { Building2, LayoutDashboard, FileText, Wallet, Plus, ShieldCheck, Users, RefreshCw, Download, ArrowDownLeft, ArrowUpRight, ChevronRight, Landmark, Clock3, CircleCheck, Search, AlertCircle, BookOpen, LogOut } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel, AlertDialogAction, AlertDialogFooter } from '@/components/ui/alert-dialog';
import { Empty, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Skeleton } from '@/components/ui/skeleton';
import { emptyLedger, today, addDays, days, yuan, formatMoney, sum, categories, billTotals, outstanding, cashSummary, type Ledger, type Bill, type Entry, type Command, type Lease } from '@/lib/ledger';
import { Choice, EditorFields, toCommand, type Draft, modeLabels } from './forms';
const nav = [{id:'overview',label:'经营概览',Icon:LayoutDashboard},{id:'properties',label:'房源与房间',Icon:Building2},{id:'tenants',label:'租客',Icon:Users},{id:'leases',label:'租赁合同',Icon:FileText},{id:'bills',label:'账单与收支',Icon:Wallet},{id:'deposits',label:'押金管理',Icon:Landmark},{id:'records',label:'流水与记录',Icon:BookOpen}];
const editorTitles:Record<string,string>={'property.save':'房源资料','tenant.save':'租客资料','lease.create':'新建租赁合同','bill.create':'新增应收 / 应付','entry.create':'登记收付款','bill.adjust':'调整账单','bill.void':'作废账单','lease.close':'提前结束合同','entry.reverse':'冲销错误流水'};
type Snapshot={state:Ledger;revision:number;user?:{name:string;email:string}};
function Blank({title,description,children}:{title:string;description?:string;children?:React.ReactNode}) {return <Empty className="empty-block"><Building2 size={32}/><EmptyTitle>{title}</EmptyTitle>{description&&<EmptyDescription>{description}</EmptyDescription>}{children}</Empty>;}
function Navigation({view,navigate}:{view:string;navigate:(v:string)=>void}) {const {setOpenMobile}=useSidebar();return <Sidebar><SidebarHeader className="brand"><span className="brand-icon"><Building2/></span><div><strong>房账</strong><small>我的出租管理</small></div></SidebarHeader><SidebarContent className="nav-area"><small className="nav-label">工作台</small><SidebarMenu>{nav.map(({id,label,Icon})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} className="nav-link" onClick={()=>{navigate(id);setOpenMobile(false);}}><Icon/>{label}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="side-foot"><ShieldCheck size={18}/><span>个人账本 · 私密访问</span></SidebarFooter></Sidebar>;}
export default function Workspace() {
 const [snapshot,setSnapshot]=useState<Snapshot>({state:emptyLedger(),revision:0});const s=snapshot.state;
 const [loaded,setLoaded]=useState(false),[syncing,setSyncing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [view,setView]=useState('overview'),[scope,setScope]=useState(''),[month,setMonth]=useState(today().slice(0,7)),[query,setQuery]=useState(''),[billFilter,setBillFilter]=useState('open'),[billSide,setBillSide]=useState('all');
 const [modal,setModal]=useState(''),[draft,setDraft]=useState<Draft>({}),[detailId,setDetailId]=useState(''),[limit,setLimit]=useState(50),[confirm,setConfirm]=useState<Command|null>(null);
 const stateRef=useRef(snapshot);stateRef.current=snapshot;
 const busyRef=useRef(false),requestRef=useRef<{key:string;signature:string}|null>(null);
 const currentDay=today();const start=month+'-01';const nextMonth=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),1)).toISOString().slice(0,10);const end=addDays(nextMonth,-1);
 const refresh=useCallback(async(silent=false)=>{if(busyRef.current)return;if(!silent)setSyncing(true);try{const r=await fetch('/api/ledger',{cache:'no-store'});const data=await r.json() as Snapshot & {error?:string};if(!r.ok)throw new Error(data.error||'加载失败');if(busyRef.current)return;setSnapshot(old=>data.revision>=old.revision?data:old);setLoaded(true);setError('');}catch(e){if(!silent)setError(e instanceof Error?e.message:'无法连接，请重试');}finally{setSyncing(false);}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 useEffect(()=>{if(modal||detailId)return;const onFocus=()=>void refresh(true);window.addEventListener('focus',onFocus);const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh(true);},30000);return()=>{window.removeEventListener('focus',onFocus);clearInterval(timer);};},[refresh,modal,detailId]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
 const navigate=(v:string)=>{setView(v);setQuery('');setLimit(50);};
 const propertyName=(id:string)=>s.properties.find(p=>p.id===id)?.name??'房源';
 const party=(b:Bill)=>{const l=s.leases.find(l=>l.id===b.leaseId);return l?leaseParty(l):'房源收支';};
 const leaseParty=(l:Lease)=>l.side==='in'?(s.tenants.find(t=>t.id===l.tenantId)?.name??'租客'):l.landlord;
 const set=(key:string,value:string)=>setDraft(old=>({...old,[key]:value}));
 const openEditor=(type:string,initial:Draft={})=>{setError('');setDetailId('');requestRef.current=null;setDraft({source:'owned',side:'in',unit:'整套',rent:'',deposit:'0',cycle:'1',advance:'0',propertyId:scope||s.properties.find(p=>!p.archived)?.id||'',tenantId:s.tenants[0]?.id||'',start:currentDay,end:currentDay,due:currentDay,date:currentDay,category:'repair',metered:'no',method:'微信',...initial});setModal(type);};
 const save=async(command:Command)=>{if(busyRef.current)return false;busyRef.current=true;setBusy(true);setError('');const signature=JSON.stringify(command);if(!requestRef.current||requestRef.current.signature!==signature)requestRef.current={key:crypto.randomUUID(),signature};const key=requestRef.current.key;
 try {const response=await fetch('/api/ledger',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command,revision:stateRef.current.revision,requestId:key})});const data=await response.json() as Snapshot & {error?:string};if(data.state){setSnapshot(old=>({...old,...data}));stateRef.current={...stateRef.current,...data};}if(!response.ok){if(response.status===409)requestRef.current=null;throw new Error(data.error||'保存失败');}requestRef.current=null;setNotice('已保存，手机和电脑可同步查看');return true;
 }catch(e){try{const r=await fetch('/api/ledger',{cache:'no-store'});if(r.ok){const fresh=await r.json() as Snapshot;setSnapshot(fresh);stateRef.current=fresh;if(fresh.state.requests.includes(key)){requestRef.current=null;setNotice('已确认保存成功');return true;}}}catch{}setError(e instanceof Error?e.message:'连接中断，请保持表单不变并重试；重复提交不会重复记账');return false;}finally{busyRef.current=false;setBusy(false);}};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(await save(toCommand(modal,draft))){setModal('');setConfirm(null);}};
 const exportData=()=>{const data=JSON.stringify({app:'房账',exportedAt:new Date().toISOString(),currency:'CNY',moneyUnit:'fen',...snapshot},null,2);download(data,'房账-'+currentDay+'.json','application/json');};
 const exportCsv=()=>{const rows=[['日期','房源','房间','类型','费用','方向','金额（元）','方式','备注','流水编号','冲销原编号'],...s.entries.filter(e=>!scope||s.bills.find(b=>b.id===e.billId)?.propertyId===scope).map(e=>{const b=s.bills.find(b=>b.id===e.billId)!;return[e.date,propertyName(b.propertyId),b.unit,entryLabel(e,b),b.title,b.side==='in'?'应收侧':'应付侧',yuan(e.amount),e.method,e.note,e.id,e.reversalOf];})];download('\ufeff'+rows.map(r=>r.map(v=>'"'+(/^[=+\-@\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'房账流水-'+currentDay+'.csv','text/csv;charset=utf-8');};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_rental_ledger_summary',description:'读取已登录用户当前账本的房源、合同数和累计经营收支。金额单位为人民币分。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('无需参数');const state=stateRef.current.state;return {revision:stateRef.current.revision,properties:state.properties.length,leases:state.leases.length,...cashSummary(state)};}},{name:'start_rental_property_creation',description:'打开新增房源表单，不保存房源。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('无需参数');setDraft({source:'owned',name:'',rooms:'',address:'',note:''});setModal('property.save');return {form:'property.save',saved:false};}}];for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const scopedBills=s.bills.filter(b=>!scope||b.propertyId===scope);const scopedLeases=s.leases.filter(l=>!scope||l.propertyId===scope);
 const dueBills=scopedBills.filter(b=>!b.voided&&b.due<=currentDay&&outstanding(s,b)>0);
 const overdueIn=sum(dueBills.filter(b=>b.side==='in').map(b=>outstanding(s,b)));
 const deposits=scopedBills.filter(b=>b.category==='deposit');const depositIn=sum(deposits.filter(b=>b.side==='in').map(b=>billTotals(s,b.id).balance));const depositOut=sum(deposits.filter(b=>b.side==='out').map(b=>billTotals(s,b.id).balance));
 const summary=cashSummary(s,start,end,scope);const cumulative=cashSummary(s,'2000-01-01',currentDay,scope);
 const expiring=scopedLeases.filter(l=>l.end>=currentDay&&l.end<=addDays(currentDay,30));
 const activeLeases=scopedLeases.filter(l=>l.side==='in'&&l.start<=currentDay&&l.end>=currentDay);
 const selectedBill=s.bills.find(b=>b.id===detailId);
 const filterBills=scopedBills.filter(b=>{if(billSide!=='all'&&b.side!==billSide)return false;if(query&&!(`${propertyName(b.propertyId)} ${b.title} ${b.unit} ${party(b)}`).includes(query))return false;return billFilter==='all'||(billFilter==='void'?b.voided:!b.voided&&(billFilter==='open'?outstanding(s,b)>0:billFilter==='due'?outstanding(s,b)>0&&b.due<=currentDay:outstanding(s,b)===0));}).sort((a,b)=>a.due.localeCompare(b.due));
 const actOnBill=(b:Bill,kind:string)=>{const t=billTotals(s,b.id),deposit=s.bills.find(d=>d.leaseId===b.leaseId&&d.category==='deposit');openEditor('entry.create',{billId:b.id,kind,depositId:deposit?.id??'',amount:yuan(kind==='refund'?(b.category==='deposit'?t.balance:t.paid-t.refunded):kind==='apply'?Math.min(t.remaining,deposit?billTotals(s,deposit.id).balance:0):t.remaining),billTitle:b.title,side:b.side});};
 function BillTable({bills}:{bills:Bill[]}) {return <Table className="ledger-table"><TableHeader><TableRow><TableHead>账单 / 房源</TableHead><TableHead className="hide-small">对象</TableHead><TableHead>应收付日期</TableHead><TableHead className="number hide-small">账单金额</TableHead><TableHead className="number">未结清</TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody>{bills.map(b=>{const t=billTotals(s,b.id);return <TableRow key={b.id}><TableCell><button className="cell-link" onClick={()=>{setError('');setDetailId(b.id);}}>{b.side==='in'?<ArrowDownLeft className="income" size={16}/>:<ArrowUpRight className="expense" size={16}/>} {b.title}<ChevronRight size={14}/></button><small>{propertyName(b.propertyId)} · {b.unit}</small></TableCell><TableCell className="hide-small">{party(b)}</TableCell><TableCell>{b.due}</TableCell><TableCell className="number hide-small">{formatMoney(b.amount)}</TableCell><TableCell className="number">{formatMoney(t.remaining)}</TableCell><TableCell><span className={'status '+(b.voided?'muted':t.remaining===0?'green':b.due<currentDay?'red':'blue')}>{b.voided?'已作废':t.remaining===0?'已结清':b.due<currentDay?'逾期':t.settled>0?'部分结清':'待'+(b.side==='in'?'收':'付')}</span></TableCell></TableRow>;})}</TableBody></Table>;}
 function EntryRows({entries}:{entries:Entry[]}) {return <Table className="ledger-table"><TableHeader><TableRow><TableHead>日期 / 项目</TableHead><TableHead>类型</TableHead><TableHead className="number">金额</TableHead><TableHead className="hide-small">备注</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{[...entries].reverse().map(e=>{const b=s.bills.find(b=>b.id===e.billId)!;const reversed=s.entries.some(x=>x.reversalOf===e.id);return <TableRow key={e.id}><TableCell>{e.date}<small>{b.title} · {propertyName(b.propertyId)} · {b.unit}</small></TableCell><TableCell>{entryLabel(e,b)}<small>{reversed?'已冲销':e.method}</small></TableCell><TableCell className="number">{formatMoney(e.amount)}</TableCell><TableCell className="hide-small wrap-cell">{e.note||'—'}</TableCell><TableCell>{e.kind!=='reversal'&&!reversed&&<Button variant="ghost" onClick={()=>openEditor('entry.reverse',{id:e.id})}>冲销</Button>}</TableCell></TableRow>;})}</TableBody></Table>;}
 return <SidebarProvider style={{'--sidebar-width':'228px'} as CSSProperties}><Navigation view={view} navigate={navigate}/><main className="workspace"><header className="topbar"><div className="flex items-center gap-3"><SidebarTrigger aria-label="展开导航"/><span>我的账本</span><span className="hide-small top-divider">/</span><span className="hide-small muted-text">{nav.find(n=>n.id===view)?.label}</span></div><div className="top-actions"><span className="sync-label"><i className={loaded?'online-dot':'offline-dot'}/>{loaded?'已连接':'连接中'}</span><Button variant="ghost" size="icon" aria-label="刷新账本" disabled={syncing||busy} onClick={()=>void refresh()}><RefreshCw size={17} className={syncing?'spin':''}/></Button><a href="/signout-with-chatgpt?return_to=%2F" title="退出登录" aria-label="退出登录"><LogOut size={17}/></a></div></header>
 <div className="page-content"><div className="page-heading"><div><div className="eyebrow">个人出租管理 · 人民币 CNY</div><h1>{view==='overview'?'每一间房，每一笔账。':nav.find(n=>n.id===view)?.label}</h1><p>{view==='overview'?currentDay+' · 查看房源经营与待办账单':view==='bills'?'先记应收应付，再登记实际收付款。':view==='deposits'?'押金独立核算，收取、退还和抵扣都有记录。':view==='leases'?'整租、分租和上游租约，按合同独立出账。':view==='records'?'每笔流水和调整均保留记录，可导出核对。':view==='tenants'?'租客联系方式及其关联租约。':'自有、租入、整套与分房间，集中管理。'}</p></div><div className="heading-actions">{view==='overview'||view==='properties'?<Button className="primary-button" disabled={!loaded} onClick={()=>openEditor('property.save')}><Plus size={18}/>添加房源</Button>:view==='tenants'?<Button className="primary-button" disabled={!loaded} onClick={()=>openEditor('tenant.save')}><Plus size={18}/>添加租客</Button>:view==='leases'?<Button className="primary-button" disabled={!loaded||s.properties.length===0} onClick={()=>openEditor('lease.create')}><Plus size={18}/>新建合同</Button>:view==='bills'?<Button className="primary-button" disabled={!loaded||s.properties.length===0} onClick={()=>openEditor('bill.create',{side:'out'})}><Plus size={18}/>新增账单 / 支出</Button>:<Button variant="outline" className="action-button" onClick={view==='records'?exportCsv:exportData} disabled={!loaded}><Download size={17}/>导出{view==='records'?'流水':'账本'}</Button>}</div></div>
 {error&&!modal&&!detailId&&<div role="alert" className="error-banner"><AlertCircle size={18}/>{error}<Button variant="ghost" onClick={()=>void refresh()}>重试</Button></div>}{notice&&<div role="status" className="success-banner"><CircleCheck size={17}/>{notice}</div>}
 {!loaded?<div className="stats-grid">{[1,2,3,4].map(n=><Skeleton className="h-40 rounded-xl" key={n}/>)}</div>:<>
 {view!=='tenants'&&<div className="scope-bar"><Choice label="房源范围" value={scope} onChange={v=>{setScope(v);setLimit(50);}} options={[["","全部房源"],...s.properties.map(p=>[p.id,p.name+(p.archived?'（归档）':'')] as [string,string])]}/>{view==='overview'&&<label className="field"><span>收支月份</span><Input type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{if(/^20\d\d-\d\d$|^2100-\d\d$/.test(e.target.value))setMonth(e.target.value);}}/></label>}<span className="scope-note">{view==='overview'?'账单和押金为截至今日状态；经营收支按所选月份统计。':snapshot.user?.name??'个人账本'}</span></div>}
 {view==='overview'&&<><div className="stats-grid"><Stat primary label="到期未收" value={overdueIn} note={dueBills.filter(b=>b.side==='in').length+' 笔到期账单（含待收押金）'}/><Stat label="本月经营实收" value={summary.operatingIn} note="扣除退款，含押金抵扣，收押不计收入"/><Stat label="本月经营实付" value={summary.operatingOut} note="含租入、装修、维修；付押不计成本"/><Stat label="租客押金余额" value={depositIn} note="已收减已退减已抵扣"/></div><div className="overview-grid"><section className="panel"><div className="panel-title"><h2>待办账单 <span className="count">{dueBills.length}</span></h2><Button variant="ghost" onClick={()=>{navigate('bills');setBillFilter('due');}}>全部账单<ChevronRight size={15}/></Button></div>{dueBills.length?<BillTable bills={dueBills.sort((a,b)=>a.due.localeCompare(b.due)).slice(0,6)}/>:<Blank title={s.properties.length?'暂无到期未结清账单':'开始建立你的房源账本'} description={s.properties.length?'新账单会在到期时出现在这里。':'添加房源 → 登记租客 → 新建合同，租金账单自动生成。'}>{!s.properties.length&&<Button variant="outline" onClick={()=>openEditor('property.save')}><Plus size={16}/>添加第一套房源</Button>}</Blank>}</section><section className="panel"><div className="panel-title"><h2>经营小结</h2><span className="pill">{month}</span></div><div className="summary-lines"><SummaryLine label="经营收支差额" value={summary.operatingNet}/><SummaryLine label="现金流入（含押金）" value={summary.cashIn}/><SummaryLine label="现金流出（含押金）" value={summary.cashOut}/><SummaryLine label="现金净流量" value={summary.cashNet} strong/><p className="form-hint">收支差额按收付时点统计，包含装修支出，未做折旧和权责摊销，不等同于利润。</p></div></section></div><div className="overview-grid section-gap"><section className="panel"><div className="panel-title"><h2>30 天内合同到期</h2><span className="pill">{expiring.length} 份</span></div>{expiring.length?<div className="reminders">{expiring.map(l=><button key={l.id} onClick={()=>navigate('leases')}><span className="reminder-icon"><Clock3 size={19}/></span><span><b>{propertyName(l.propertyId)} · {l.unit}</b><small>{leaseParty(l)} · {l.side==='in'?'出租':'上游'}合同</small></span><span className="reminder-date">{l.end}<small>{days(currentDay,l.end)} 天后到期</small></span></button>)}</div>:<div className="quiet-empty"><CircleCheck size={20}/>近期没有到期合同</div>}</section><section className="panel"><div className="panel-title"><h2>房源与资金</h2></div><div className="summary-lines"><div className="summary-line"><span>当前生效出租合同</span><b>{activeLeases.length} 份</b></div><SummaryLine label="付给上游的押金余额" value={depositOut}/><SummaryLine label="累计现金净流量" value={cumulative.cashNet}/><Button variant="outline" className="w-full action-button" onClick={exportData}><Download size={16}/>导出完整账本备份</Button></div></section></div></>}
 {view==='properties'&&<div className="property-grid">{s.properties.filter(p=>!scope||p.id===scope).map(p=>{const leases=s.leases.filter(l=>l.propertyId===p.id&&l.side==='in'&&l.start<=currentDay&&l.end>=currentDay);const cash=cashSummary(s,'2000-01-01',currentDay,p.id);return <section className="panel property-card" key={p.id}><div className="property-top"><span className="property-icon"><Building2 size={25}/></span><span className={'status '+(p.archived?'muted':p.source==='owned'?'blue':'amber')}>{p.archived?'已归档':p.source==='owned'?'自有':'租入再出租'}</span></div><h2>{p.name}</h2><p className="address">{p.address||'未填写地址'}</p><div className="room-grid">{(p.rooms.length?p.rooms:['整套']).map(room=>{const occupied=leases.some(l=>l.unit==='整套'||l.unit===room);return <span key={room} className={'room '+(occupied?'occupied':'')}><i/>{room}<small>{occupied?'在租':'空置'}</small></span>;})}</div><div className="property-numbers"><div><small>累计经营实收</small><b>{formatMoney(cash.operatingIn)}</b></div><div><small>累计经营实付</small><b>{formatMoney(cash.operatingOut)}</b></div></div>{p.note&&<p className="card-note">{p.note}</p>}<div className="card-actions"><Button variant="ghost" onClick={()=>openEditor('property.save',{id:p.id,name:p.name,address:p.address,source:p.source,rooms:p.rooms.join('\n'),note:p.note})}>编辑资料</Button><Button variant="ghost" onClick={()=>{setScope(p.id);navigate('bills');}}>查看账单<ChevronRight size={14}/></Button><Button variant="ghost" onClick={()=>setConfirm({type:'property.archive',id:p.id})}>{p.archived?'恢复':'归档'}</Button></div></section>;})}{s.properties.length===0&&<section className="panel wide"><Blank title="还没有房源" description="先添加房源，可以同时管理整租和分租。"><Button onClick={()=>openEditor('property.save')}>添加房源</Button></Blank></section>}</div>}
 {view==='tenants'&&<section className="panel"><div className="panel-title"><h2>租客档案 <span className="count">{s.tenants.length}</span></h2><div className="search-field"><Search size={17}/><Input aria-label="搜索租客" placeholder="姓名 / 电话" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{s.tenants.length?<Table className="ledger-table"><TableHeader><TableRow><TableHead>姓名</TableHead><TableHead>联系电话</TableHead><TableHead>关联合同</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{s.tenants.filter(t=>(t.name+' '+t.phone).includes(query)).map(t=><TableRow key={t.id}><TableCell><b>{t.name}</b><small className="wrap-cell">{t.note}</small></TableCell><TableCell>{t.phone||'—'}</TableCell><TableCell>{s.leases.filter(l=>l.tenantId===t.id).map(l=><small className="lease-reference" key={l.id}>{propertyName(l.propertyId)} · {l.unit}<br/>{l.start} ~ {l.end}</small>)}</TableCell><TableCell><Button variant="ghost" onClick={()=>openEditor('tenant.save',{...t})}>编辑</Button></TableCell></TableRow>)}</TableBody></Table>:<Blank title="还没有租客" description="填写姓名与联系方式后，即可关联合同。"><Button onClick={()=>openEditor('tenant.save')}>登记租客</Button></Blank>}</section>}
 {view==='leases'&&<>{!s.tenants.length&&<div className="info-banner">签出租合同前，请先登记租客。<Button variant="ghost" onClick={()=>openEditor('tenant.save')}>添加租客<ChevronRight size={15}/></Button></div>}<div className="lease-list">{scopedLeases.map(l=><section className="panel lease-card" key={l.id}><div className="lease-heading"><div><span className={'status '+(l.side==='in'?'blue':'amber')}>{l.side==='in'?'出租合同':'上游合同'}</span><h2>{propertyName(l.propertyId)} <span> / {l.unit}</span></h2><p>{leaseParty(l)}{l.phone?' · '+l.phone:''}</p></div><span className={'status '+(l.end<currentDay?'muted':l.start>currentDay?'blue':'green')}>{l.end<currentDay?'已结束':l.start>currentDay?'待起租':'生效中'}</span></div><div className="lease-data"><div><small>合同期限（含结束日）</small><b>{l.start} ~ {l.end}</b></div><div><small>月租金</small><b>{formatMoney(l.rent)}</b></div><div><small>约定押金</small><b>{formatMoney(l.deposit)}</b></div><div><small>付款规则</small><b>每 {l.cycle} 个月 · 提前 {l.advance} 天</b></div></div>{l.fees.length>0&&<div className="fee-tags">{l.fees.map(f=><span key={f.category}>{categories[f.category]}：{modeLabels[f.mode]}{f.mode==='fixed'?' '+formatMoney(f.amount)+'/月':f.mode==='metered'?' '+f.rate+' 元/单位':''}</span>)}</div>}{l.note&&<p className="card-note">{l.note}</p>}{l.closed&&<p className="form-hint">已提前结束，原合同到期日 {l.originalEnd}。</p>}<div className="card-actions"><Button variant="ghost" onClick={()=>{setScope(l.propertyId);setView('bills');setBillFilter('all');setQuery(leaseParty(l));}}>查看账单<ChevronRight size={14}/></Button><Button variant="ghost" onClick={()=>openEditor('bill.create',{propertyId:l.propertyId,leaseId:l.id,unit:l.unit,side:l.side,category:'water',start:l.start,end:l.end,metered:l.fees.find(f=>f.category==='water')?.mode==='metered'?'yes':'no',rate:l.fees.find(f=>f.category==='water')?.rate??''})}>新增杂费</Button><Button variant="ghost" onClick={()=>openEditor('lease.close',{id:l.id,end:l.end})}>提前结束</Button></div></section>)}</div>{scopedLeases.length===0&&<section className="panel"><Blank title="还没有租赁合同" description="可分别建立出租合同和一手房东的上游合同，保存前可核对全部账单。"><Button disabled={!s.properties.length} onClick={()=>openEditor('lease.create')}>新建合同</Button></Blank></section>}</>}
 {view==='bills'&&<section className="panel"><div className="bill-toolbar"><Tabs value={billFilter} onValueChange={v=>{setBillFilter(String(v));setLimit(50);}}><TabsList className="filter-tabs">{[['open','未结清'],['due','已到期'],['settled','已结清'],['all','全部'],['void','已作废']].map(([v,t])=><TabsTrigger key={v} value={v}>{t}</TabsTrigger>)}</TabsList></Tabs><div className="filter-row"><Choice label="方向" value={billSide} onChange={setBillSide} options={[["all","收支全部"],["in","应收"],["out","应付"]]}/><div className="search-field"><Search size={17}/><Input aria-label="搜索账单" placeholder="房源 / 租客 / 费用" value={query} onChange={e=>{setQuery(e.target.value);setLimit(50);}}/></div></div></div>{filterBills.length?<><div className="table-summary">共 {filterBills.length} 笔 · 未结清应收 {formatMoney(sum(filterBills.filter(b=>b.side==='in').map(b=>outstanding(s,b))))} · 未结清应付 {formatMoney(sum(filterBills.filter(b=>b.side==='out').map(b=>outstanding(s,b))))}</div><BillTable bills={filterBills.slice(0,limit)}/>{filterBills.length>limit&&<Button variant="ghost" className="more-button" onClick={()=>setLimit(limit+50)}>显示更多（{limit} / {filterBills.length}）</Button>}</>:<Blank title="没有符合条件的账单" description="新建合同会自动生成租金和押金账单；维修、装修等可手动新增。"/>}</section>}
 {view==='deposits'&&<><div className="deposit-stats"><Stat primary label="持有租客押金" value={depositIn} note="已收 − 已退 − 已抵扣"/><Stat label="留在上游的押金" value={depositOut} note="已付 − 已收回 − 已抵扣"/></div><section className="panel"><div className="panel-title"><h2>合同押金明细</h2></div>{deposits.length?<Table className="ledger-table"><TableHeader><TableRow><TableHead>房源 / 对象</TableHead><TableHead className="number">约定押金</TableHead><TableHead className="number">已收 / 已付</TableHead><TableHead className="number">已退 / 抵扣</TableHead><TableHead className="number">剩余押金</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{deposits.map(b=>{const t=billTotals(s,b.id);return <TableRow key={b.id}><TableCell><b>{propertyName(b.propertyId)} · {b.unit}</b><small>{party(b)} · {b.side==='in'?'租客押金':'上游押金'}</small></TableCell><TableCell className="number">{formatMoney(b.amount)}</TableCell><TableCell className="number">{formatMoney(t.paid)}</TableCell><TableCell className="number">{formatMoney(t.refunded)}<small>抵扣 {formatMoney(t.applied)}</small></TableCell><TableCell className="number strong-number">{formatMoney(t.balance)}</TableCell><TableCell><Button variant="ghost" onClick={()=>{setError('');setDetailId(b.id);}}>管理</Button></TableCell></TableRow>;})}</TableBody></Table>:<Blank title="暂无押金账单" description="新建合同时填写押金金额，收到或付出押金后再登记流水。"/>}</section><p className="bottom-note">押金抵扣：进入对应租金或杂费账单，选择“押金抵扣”。仅可使用同一合同的押金。</p></>}
 {view==='records'&&<><div className="record-actions"><Button variant="outline" onClick={exportData}><Download size={16}/>完整账本 JSON</Button><span className="form-hint">CSV 导出当前房源范围全部流水；JSON 保存所有房源、合同、账单与记录。</span></div><section className="panel"><div className="panel-title"><h2>收付款流水</h2><span className="pill">按实际日期记账</span></div>{s.entries.filter(e=>!scope||s.bills.find(b=>b.id===e.billId)?.propertyId===scope).length?<><EntryRows entries={s.entries.filter(e=>!scope||s.bills.find(b=>b.id===e.billId)?.propertyId===scope).slice(-limit)}/>{s.entries.length>limit&&<Button variant="ghost" className="more-button" onClick={()=>setLimit(limit+50)}>显示更多</Button>}</>:<Blank title="还没有实际收付款" description="在账单中登记收款、付款、退款或押金抵扣后，流水会显示在这里。"/>}</section><section className="panel section-gap"><div className="panel-title"><h2>操作记录</h2><span className="muted-text">全部房源 · 最近 100 条</span></div><div className="audit-list">{s.audit.length?[...s.audit].reverse().slice(0,100).map(a=><div key={a.id}><span>{new Date(a.at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}</span><p>{a.note}</p></div>):<div className="quiet-empty">暂无操作记录</div>}</div></section></>}
 </>}
 </div></main>
 <Dialog open={!!modal} onOpenChange={o=>{if(!o&&!busy){setModal('');setError('');}}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{modal==='entry.create'?(draft.kind==='apply'?'押金抵扣':draft.kind==='refund'?(draft.side==='out'?'登记收回退款':'登记退款'):(draft.side==='out'?'登记付款':'登记收款')):editorTitles[modal]??'编辑'}</DialogTitle><DialogDescription>{modal==='entry.create'?draft.billTitle:'填写后保存到你的个人账本。'}</DialogDescription></DialogHeader><form onSubmit={submit}><fieldset disabled={busy}><EditorFields type={modal} d={draft} set={set} s={s}/></fieldset>{error&&<div role="alert" className="error-banner">{error}</div>}<div className="form-actions"><Button type="button" variant="outline" onClick={()=>setModal('')} disabled={busy}>取消</Button><Button type="submit" className="primary-button" disabled={busy}>{busy?'保存中…':modal==='lease.create'?'确认合同并生成账单':'确认保存'}</Button></div></form></DialogContent></Dialog>
 <Dialog open={!!selectedBill} onOpenChange={o=>{if(!o)setDetailId('');}}><DialogContent className="editor-dialog detail-dialog"><DialogHeader><DialogTitle>{selectedBill?.title}</DialogTitle><DialogDescription>{selectedBill?propertyName(selectedBill.propertyId)+' · '+selectedBill.unit+' · '+party(selectedBill):''}</DialogDescription></DialogHeader>{selectedBill&&(()=>{const b=selectedBill,t=billTotals(s,b.id),d=s.bills.find(x=>x.leaseId===b.leaseId&&x.category==='deposit');return <><div className="detail-amount"><span>{b.side==='in'?'应收':'应付'}总额</span><b>{formatMoney(b.amount)}</b><span className="status blue">{b.voided?'已作废':b.category==='deposit'?'押金余额 '+formatMoney(t.balance):'未结清 '+formatMoney(t.remaining)}</span></div><div className="detail-meta"><p>应收付日期 <b>{b.due}</b></p><p>费用期间 <b>{b.start} 至 {b.end}</b></p><p>已收付 {formatMoney(t.paid)} · 已退 {formatMoney(t.refunded)} · 已抵扣 {formatMoney(t.applied)}</p></div>{b.note&&<p className="detail-note">{b.note}</p>}<div className="detail-actions">{!b.voided&&t.remaining>0&&<Button className="primary-button" onClick={()=>actOnBill(b,'payment')}>{b.side==='in'?'登记收款':'登记付款'}</Button>}{!b.voided&&(b.category==='deposit'?t.balance>0:t.paid-t.refunded>0)&&<Button variant="outline" onClick={()=>actOnBill(b,'refund')}>{b.category==='deposit'?(b.side==='in'?'退还押金':'收回上游押金'):(b.side==='in'?'退款给对方':'收回退款')}</Button>}{!b.voided&&b.category!=='deposit'&&t.remaining>0&&d&&billTotals(s,d.id).balance>0&&<Button variant="outline" onClick={()=>actOnBill(b,'apply')}>押金抵扣</Button>}{!b.voided&&b.category!=='deposit'&&<><Button variant="ghost" onClick={()=>openEditor('bill.adjust',{id:b.id,amount:yuan(b.amount),due:b.due})}>调整账单</Button>{t.settled===0&&<Button variant="ghost" onClick={()=>openEditor('bill.void',{id:b.id})}>作废</Button>}</>}</div><h3 className="detail-subtitle">此账单的相关流水</h3>{s.entries.some(e=>e.billId===b.id||e.depositId===b.id)?<EntryRows entries={s.entries.filter(e=>e.billId===b.id||e.depositId===b.id)}/>:<p className="form-hint">尚未登记收付款。</p>}</>;})()}</DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={o=>{if(!o&&!busy)setConfirm(null);}}><AlertDialogContent><AlertDialogTitle>更改房源归档状态</AlertDialogTitle><AlertDialogDescription>历史合同和账目会保留。有未结束合同、未结账单或剩余押金时，系统会阻止归档。</AlertDialogDescription>{error&&<p role="alert" className="error-text">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{if(confirm&&await save(confirm))setConfirm(null);}}>确认</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
function Stat({label,value,note,primary=false}:{label:string;value:number;note:string;primary?:boolean}) {return <section className={'stat '+(primary?'stat-primary':'')}><div className="stat-label">{label}<ArrowUpRight size={17}/></div><div className="stat-value">{formatMoney(value)}</div><p>{note}</p></section>;}
function SummaryLine({label,value,strong=false}:{label:string;value:number;strong?:boolean}) {return <div className={'summary-line '+(strong?'strong':'')}><span>{label}</span><b>{formatMoney(value)}</b></div>;}
function entryLabel(e:Entry,b:Bill) {return e.kind==='reversal'?'冲销':e.kind==='apply'?'押金抵扣':e.kind==='refund'?(b.side==='in'?'退款支出':'退款收回'):(b.side==='in'?'实际收款':'实际付款');}
function download(content:string,name:string,type:string) {const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
