// Currency is integer fen. Decimal parsing, metering and prorating never use floating-point arithmetic.
export const categories = { rent:'租金', deposit:'押金', water:'水费', electricity:'电费', internet:'网费', propertyFee:'物业费', decoration:'装修', repair:'维修', other:'其他' } as const;
export type Category = keyof typeof categories;
export type Side = 'in' | 'out';
export type FeeMode = 'self' | 'manual' | 'metered' | 'fixed';
export type FeeRule = { category: Category; mode: FeeMode; amount: number; rate: string };
export type Property = { id:string; name:string; address:string; source:'owned'|'leased'; rooms:string[]; note:string; archived:boolean };
export type Tenant = { id:string; name:string; phone:string; note:string };
export type Lease = { id:string; propertyId:string; unit:string; side:Side; tenantId:string; landlord:string; phone:string; start:string; end:string; originalEnd:string; rent:number; deposit:number; cycle:number; advance:number; fees:FeeRule[]; note:string; closed:boolean };
export type Bill = { id:string; propertyId:string; unit:string; leaseId:string; category:Category; side:Side; title:string; amount:number; due:string; start:string; end:string; note:string; automatic:boolean; voided:boolean };
export type Entry = { id:string; kind:'payment'|'refund'|'apply'|'reversal'; billId:string; depositId:string; amount:number; date:string; method:string; note:string; reversalOf:string; createdAt:string };
export type Audit = { id:string; at:string; action:string; note:string };
export type Ledger = { schema:1; properties:Property[]; tenants:Tenant[]; leases:Lease[]; bills:Bill[]; entries:Entry[]; audit:Audit[]; requests:string[] };
export type Command = { type:string; [key:string]:unknown };
const MAX = 100_000_000_000;
export function check(value:unknown,message:string): asserts value { if(!value) throw new Error(message); }
export const emptyLedger = ():Ledger => ({schema:1,properties:[],tenants:[],leases:[],bills:[],entries:[],audit:[],requests:[]});
export const uid = () => crypto.randomUUID();
export function text(value:unknown,label='内容',required=false,max=1000) { check(typeof value==='string',label+'格式无效');const s=value.trim(); check(s.length<=max && (!required||s.length>0),label+'不能为空或过长');return s; }
export function integer(value:unknown,min:number,max:number,label='数值') { const n=typeof value==='string'&&/^\d+$/.test(value)?Number(value):value;check(typeof n==='number'&&Number.isSafeInteger(n)&&n>=min&&n<=max,label+'超出范围');return n; }
export function scaled(value:unknown,places:number,label='金额'):number { check(typeof value==='string' && new RegExp('^\\d{1,12}(?:\\.\\d{1,'+places+'})?$').test(value),label+'须为非负数，最多'+places+'位小数'); const [a,b='']=value.split('.');const n=BigInt(a)*10n**BigInt(places)+BigInt(b.padEnd(places,'0'));check(n<=BigInt(MAX),label+'过大');return Number(n); }
export const money = (v:unknown) => scaled(v,2);
export const yuan = (n:number) => (n<0?'-':'')+Math.floor(Math.abs(n)/100)+'.'+String(Math.abs(n)%100).padStart(2,'0');
export const formatMoney = (n:number) => '¥ '+yuan(n).replace(/\B(?=(\d{3})+(?!\d))/g,',');
export function sum(ns:number[]) { const v=ns.reduce((a,b)=>a+BigInt(b),0n);check(v<=BigInt(Number.MAX_SAFE_INTEGER)&&v>=BigInt(-Number.MAX_SAFE_INTEGER),'累计金额超出安全范围');return Number(v); }
export function rounded(n:bigint,d:bigint) { check(n>=0n&&d>0n,'无效计算'); const r=(n+d/2n)/d;check(r<=BigInt(MAX),'计算金额过大');return Number(r); }
export function meterAmount(previous:unknown,current:unknown,rate:unknown) { const a=scaled(previous,3,'上期表数'),b=scaled(current,3,'本期表数'),r=scaled(rate,4,'单价');check(b>=a,'本期表数不能小于上期表数');return rounded(BigInt(b-a)*BigInt(r),100000n); }
export function date(v:unknown):string { check(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v),'日期格式无效');check(v>='2000-01-01'&&v<='2100-12-31'&&!Number.isNaN(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'日期无效（支持 2000–2100 年）');return v; }
export const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const addDays = (s:string,n:number) => new Date(Date.parse(s+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
export const days = (a:string,b:string) => Math.round((Date.parse(b+'T00:00:00Z')-Date.parse(a+'T00:00:00Z'))/86400000);
export function addMonths(s:string,n:number) { const [y,m,d]=s.split('-').map(Number); const dt=new Date(Date.UTC(y,m-1+n,1));const last=new Date(Date.UTC(dt.getUTCFullYear(),dt.getUTCMonth()+1,0)).getUTCDate();dt.setUTCDate(Math.min(d,last));return dt.toISOString().slice(0,10); }
function get<T extends {id:string}>(items:T[],id:unknown,label:string):T {const x=items.find(i=>i.id===id);check(x,label+'不存在');return x;}
export function monthlySegments(start:string,end:string,amount:number) { const stop=addDays(end,1); const rows:{start:string;end:string;amount:number}[]=[];for(let i=0;i<120&&addMonths(start,i)<stop;i++){const a=addMonths(start,i),b=addMonths(start,i+1),e=b<stop?b:stop;rows.push({start:a,end:addDays(e,-1),amount:rounded(BigInt(amount)*BigInt(days(a,e)),BigInt(days(a,b)))});}check(addMonths(start,120)>=stop,'单份合同最长支持 10 年');return rows; }
export function leaseBills(l:Lease):Bill[] {const segments=monthlySegments(l.start,l.end,l.rent); const result:Bill[]=[];const base={propertyId:l.propertyId,unit:l.unit,leaseId:l.id,side:l.side,note:'按起租日计租；不足一个租约月按该月实际天数折算至分。',automatic:true,voided:false};for(let i=0;i<segments.length;i+=l.cycle){const part=segments.slice(i,i+l.cycle);result.push({...base,id:l.id+':rent:'+part[0].start,category:'rent',title:l.side==='in'?'租金':'上游租金',amount:sum(part.map(p=>p.amount)),due:addDays(part[0].start,-l.advance),start:part[0].start,end:part.at(-1)!.end});}if(l.deposit>0)result.push({...base,id:l.id+':deposit',category:'deposit',title:l.side==='in'?'租客押金':'上游押金',amount:l.deposit,due:addDays(l.start,-l.advance),start:l.start,end:l.start,note:'押金单独核算，不计入经营收支。'});for(const f of l.fees.filter(f=>f.mode==='fixed'))for(const p of monthlySegments(l.start,l.end,f.amount))result.push({...base,id:l.id+':'+f.category+':'+p.start,category:f.category,title:categories[f.category],amount:p.amount,due:addDays(p.start,-l.advance),start:p.start,end:p.end});return result.filter(b=>b.amount>0); }
export function entryEffects(s:Ledger) {const entries=new Map(s.entries.map(e=>[e.id,e]));return s.entries.map(e=>{if(e.kind!=='reversal')return {entry:e,sign:1,date:e.date};const original=entries.get(e.reversalOf);check(original,'原流水不存在');return {entry:original,sign:-1,date:e.date};});}
const billCache=new WeakMap<Ledger,{length:number;values:Map<string,Bill>}>();
function billsById(s:Ledger) {const cached=billCache.get(s);if(cached?.length===s.bills.length)return cached.values;const values=new Map(s.bills.map(b=>[b.id,b]));billCache.set(s,{length:s.bills.length,values});return values;}
const totalCache=new WeakMap<Ledger,{length:number;values:Map<string,{paid:number;refunded:number;applied:number}>}>();
function totalsByBill(s:Ledger) {const cached=totalCache.get(s);if(cached?.length===s.entries.length)return cached.values;const values=new Map<string,{paid:number;refunded:number;applied:number}>();const row=(id:string)=>{if(!values.has(id))values.set(id,{paid:0,refunded:0,applied:0});return values.get(id)!;};for(const {entry:e,sign} of entryEffects(s)){const t=row(e.billId);if(e.kind==='payment')t.paid+=sign*e.amount;if(e.kind==='refund')t.refunded+=sign*e.amount;if(e.kind==='apply'){t.applied+=sign*e.amount;row(e.depositId).applied+=sign*e.amount;}}totalCache.set(s,{length:s.entries.length,values});return values;}
export function billTotals(s:Ledger,id:string) {const b=billsById(s).get(id);check(b,'账单不存在');const {paid,refunded,applied}=totalsByBill(s).get(id)??{paid:0,refunded:0,applied:0};
 const settled=b.category==='deposit'?paid:paid-refunded+applied;return {paid,refunded,applied,settled,remaining:b.voided?0:b.amount-settled,balance:b.category==='deposit'?paid-refunded-applied:0}; }
export function outstanding(s:Ledger,b:Bill) {return billTotals(s,b.id).remaining;}
export function cashSummary(s:Ledger,start='2000-01-01',end='2100-12-31',propertyId='') {let operatingIn=0,operatingOut=0,cashIn=0,cashOut=0;for(const {entry:e,sign,date:d} of entryEffects(s)){if(d<start||d>end)continue;const b=get(s.bills,e.billId,'账单');if(propertyId&&b.propertyId!==propertyId)continue;const value=e.amount*sign*(e.kind==='refund'?-1:1);if(e.kind!=='apply'){const flow=e.amount*sign;const incoming=e.kind==='refund'?b.side==='out':b.side==='in';if(incoming)cashIn+=flow;else cashOut+=flow;}if(b.category!=='deposit'){if(b.side==='in')operatingIn+=value;else operatingOut+=value;}}
return {operatingIn,operatingOut,cashIn,cashOut,cashNet:cashIn-cashOut,operatingNet:operatingIn-operatingOut}; }
export function validateFinancials(s:Ledger) {for(const b of s.bills){check(Number.isSafeInteger(b.amount)&&b.amount>0&&b.amount<=MAX,'账单金额无效');const t=billTotals(s,b.id);check(t.paid>=0&&t.refunded>=0&&t.applied>=0,'流水冲销会造成负数');check(t.settled>=0&&t.settled<=b.amount,'操作后已结算金额将超过应收应付，请先退款或冲销相关流水');if(b.category==='deposit')check(t.balance>=0,'操作后押金余额不足，请先冲销抵扣或退押流水');if(b.voided)check(t.settled===0,'已结算账单不能作废');}
 // Date-level cash availability: a refund or deposit transfer cannot predate the money funding it.
 const effects=entryEffects(s).sort((a,b)=>a.date.localeCompare(b.date));const balances=new Map<string,number>();const billMap=new Map(s.bills.map(b=>[b.id,b]));const add=(id:string,n:number)=>balances.set(id,(balances.get(id)??0)+n);
 for(let i=0;i<effects.length;){const d=effects[i].date;const changed=new Set<string>();while(i<effects.length&&effects[i].date===d){const {entry:e,sign}=effects[i++];if(e.kind==='payment')add(e.billId,sign*e.amount);if(e.kind==='refund')add(e.billId,-sign*e.amount);changed.add(e.billId);if(e.kind==='apply'){add(e.depositId,-sign*e.amount);changed.add(e.depositId);}}for(const id of changed)check((balances.get(id)??0)>=0,(billMap.get(id)?.category==='deposit'?'押金':'退款')+'在 '+d+' 的可用余额不足，请核对收付日期');}
}
export function parseLease(s:Ledger,c:Command,id=uid()):Lease {const p=get(s.properties,c.propertyId,'房源');check(!p.archived,'房源已归档');const side=c.side;check(side==='in'||side==='out','合同方向无效');const unit=text(c.unit,'房间',true,80);check(unit==='整套'||p.rooms.includes(unit),'房间不属于此房源');check(side!=='out'||(p.source==='leased'&&unit==='整套'),'上游合同仅适用于租入房源的整套');const start=date(c.start),end=date(c.end);check(end>=start,'结束日期不能早于起租日');check(end<addMonths(start,120),'单份合同最长支持 10 年');const tenantId=side==='in'?get(s.tenants,c.tenantId,'租客').id:'';const feesInput=c.fees??[];check(Array.isArray(feesInput)&&feesInput.length<=4,'费用规则无效');const feeCats=['water','electricity','internet','propertyFee'];const fees:FeeRule[]=feesInput.map(f=>{check(f&&typeof f==='object'&&feeCats.includes(f.category),'费用类型无效');check(['self','manual','metered','fixed'].includes(f.mode),'费用模式无效');const amount=f.mode==='fixed'?money(f.amount):0;check(f.mode!=='fixed'||amount>0,'固定费用须大于零');const rate=f.mode==='metered'?text(f.rate,'单价',true):'0';if(f.mode==='metered')check(scaled(rate,4,'单价')>0,'单价须大于零');return {category:f.category,mode:f.mode,amount,rate};});check(new Set(fees.map(f=>f.category)).size===fees.length,'费用类型重复');const l:Lease={id,propertyId:p.id,unit,side,tenantId,landlord:side==='out'?text(c.landlord,'房东姓名',true,100):'',phone:text(c.phone??'','电话',false,80),start,end,originalEnd:end,rent:money(c.rent),deposit:money(c.deposit),cycle:integer(c.cycle,1,12,'付款周期'),advance:integer(c.advance,0,90,'提前付款天数'),fees,note:text(c.note??'','备注'),closed:false};check(l.rent>0,'月租须大于零');check(!s.leases.some(o=>o.id!==id&&o.propertyId===p.id&&o.side===side&&o.start<=end&&o.end>=start&&(o.unit==='整套'||unit==='整套'||o.unit===unit)),'该房源在此租期存在重叠合同；整租与分租也不能重叠');leaseBills(l);return l; }
export function applyCommand(source:Ledger,c:Command,requestId=uid()):Ledger {check(c&&typeof c==='object','请求无效');check(typeof requestId==='string'&&requestId.length>=8&&requestId.length<=100,'请求编号无效');if(source.requests.includes(requestId))return source;if(c.type==='expense.create'){const key=requestId.slice(0,80);const withBill=applyCommand(source,{...c,type:'bill.create',side:'out',leaseId:'',due:c.date,start:c.date,end:c.date},key+':bill');const bill=withBill.bills.at(-1)!;const result=applyCommand(withBill,{type:'entry.create',kind:'payment',billId:bill.id,amount: c.amount,date:c.date,method:c.method,note:c.note},key+':payment');result.requests.push(requestId);return result;}const s=structuredClone(source);const at=new Date().toISOString();let audit='';
 if(c.type==='property.save'){const existing=c.id?get(s.properties,c.id,'房源'):undefined;const rooms=text(c.rooms??'','房间列表').split(/[\n,，]/).map(x=>x.trim()).filter(Boolean);check(rooms.length<=50&&new Set(rooms).size===rooms.length&&rooms.every(x=>x.length<=80&&x!=='整套'),'房间名称须唯一、不能使用“整套”，最多 50 间');check(c.source==='owned'||c.source==='leased','房源来源无效');if(existing){check(s.leases.filter(l=>l.propertyId===existing.id&&l.unit!=='整套').every(l=>rooms.includes(l.unit)),'已有关联合同的房间不能移除');check(existing.source===c.source||!s.leases.some(l=>l.propertyId===existing.id&&l.side==='out'),'有上游合同时不能改为自有');}const p:Property={id:existing?.id??uid(),name:text(c.name,'房源名称',true,100),address:text(c.address??'','地址',false,300),source:c.source,rooms,note:text(c.note??'','备注'),archived:existing?.archived??false};if(existing)Object.assign(existing,p);else s.properties.push(p);audit='保存房源：'+p.name;}
 else if(c.type==='property.archive'){const p=get(s.properties,c.id,'房源');check(!s.leases.some(l=>l.propertyId===p.id&&l.end>=today()),'仍有未结束的合同，不能归档');check(!s.bills.some(b=>b.propertyId===p.id&&(outstanding(s,b)>0||billTotals(s,b.id).balance>0)),'请先结清房源账单和押金');p.archived=!p.archived;audit=(p.archived?'归档':'恢复')+'房源：'+p.name;}
 else if(c.type==='tenant.save'){const old=c.id?get(s.tenants,c.id,'租客'):undefined;const t={id:old?.id??uid(),name:text(c.name,'租客姓名',true,100),phone:text(c.phone??'','电话',false,80),note:text(c.note??'','备注')};if(old)Object.assign(old,t);else s.tenants.push(t);audit='保存租客：'+t.name;}
 else if(c.type==='lease.create'){const l=parseLease(s,c);s.leases.push(l);s.bills.push(...leaseBills(l));audit='新建'+(l.side==='in'?'出租':'上游')+'合同：'+l.start+' 至 '+l.end;}
 else if(c.type==='lease.close'){const l=get(s.leases,c.id,'合同');const end=date(c.end);check(end>=l.start&&end<l.end,'提前结束日期须在当前租期内');const note=text(c.note,'结束原因',true);if(l.side==='out')check(!s.leases.some(o=>o.side==='in'&&o.propertyId===l.propertyId&&o.start<=l.end&&o.end>end),'请先处理超过此日期的出租合同');const next=leaseBills({...l,end});for(const b of s.bills.filter(b=>b.leaseId===l.id&&b.automatic&&b.category!=='deposit')){const replacement=next.find(n=>n.id===b.id);if(replacement){b.amount=replacement.amount;b.end=replacement.end;}else b.voided=true;}
 l.end=end;l.closed=true;audit='合同提前结束至 '+end+'：'+note+'。自动账单按新租期重算，手动账单和押金保留。';}
 else if(c.type==='bill.create'){const p=get(s.properties,c.propertyId,'房源');check(!p.archived,'房源已归档');const l=c.leaseId?get(s.leases,c.leaseId,'合同'):null;check(!l||l.propertyId===p.id,'合同与房源不匹配');const side=c.side;check(side==='in'||side==='out','账单方向无效');const category=c.category;check(typeof category==='string'&&Object.hasOwn(categories,category)&&category!=='deposit','押金请通过合同管理');check(category!=='rent'||!l,'合同租金请调整自动账单，避免重复出账');check(!l||l.side===side,'账单方向与合同不匹配');const rule=l?.fees.find(f=>f.category===category);check(!rule||rule.mode!=='self','该合同此费用由租客自行缴纳，不应生成代收账单');check(!rule||rule.mode!=='fixed','该合同此费用已按固定月费自动出账');let amount=money(c.amount??'0'),note=text(c.note??'','备注');if(c.metered===true){check(category==='water'||category==='electricity','仅水电支持表数计算');amount=meterAmount(c.previous,c.current,c.rate);note='表数 '+c.previous+' → '+c.current+' × 单价 '+c.rate+' 元；'+note;}check(amount>0,'账单金额须大于零');const due=date(c.due);const start=c.start?date(c.start):due,end=c.end?date(c.end):start;check(end>=start,'费用结束日期无效');if(l)check(start>=l.start&&end<=l.end,'费用期间须在合同租期内');if(l&&['water','electricity','internet','propertyFee'].includes(category))check(!s.bills.some(b=>!b.voided&&b.leaseId===l.id&&b.category===category&&b.start<=end&&b.end>=start),'该合同此费用期间已有账单，请核对或调整原账单');const unit=l?.unit??text(c.unit??'整套','房间',true,80);check(unit==='整套'||p.rooms.includes(unit),'房间不存在');const b:Bill={id:uid(),propertyId:p.id,unit,leaseId:l?.id??'',side,category:category as Category,title:text(c.title||categories[category as Category],'费用说明',true,100),amount,due,start,end,note,automatic:false,voided:false};s.bills.push(b);audit='新增'+(side==='in'?'应收':'应付')+'账单：'+b.title+' '+yuan(amount)+' 元';}
 else if(c.type==='bill.adjust'){const b=get(s.bills,c.id,'账单');check(!b.voided,'账单已作废');check(b.category!=='deposit','合同押金金额不能修改，请通过收退押流水记录实际金额');const amount=money(c.amount);check(amount>0,'金额须大于零');audit='调整账单 '+b.title+'：'+yuan(b.amount)+' → '+yuan(amount)+' 元；'+text(c.note,'调整原因',true);b.amount=amount;b.due=date(c.due);b.note+='\n'+audit;b.automatic=false;}
 else if(c.type==='bill.void'){const b=get(s.bills,c.id,'账单');check(b.category!=='deposit','押金账单保留，请办理退押');check(!b.voided,'账单已作废');check(billTotals(s,b.id).settled===0,'已有结算，请先退款或冲销');b.voided=true;b.automatic=false;audit='作废账单 '+b.title+'：'+text(c.note,'作废原因',true);}
 else if(c.type==='entry.create'){const b=get(s.bills,c.billId,'账单');check(!b.voided,'账单已作废');const kind=c.kind;check(kind==='payment'||kind==='refund'||kind==='apply','流水类型无效');const amount=money(c.amount);check(amount>0,'金额须大于零');const d=date(c.date);check(d<=today(),'实收实付不能记录未来日期');const totals=billTotals(s,b.id);let depositId='';if(kind==='payment')check(amount<=totals.remaining,'金额超过账单未结清金额');if(kind==='refund'){check(amount<=(b.category==='deposit'?totals.balance:totals.paid-totals.refunded),'退款超过可退金额');}if(kind==='apply'){check(b.category!=='deposit'&&b.leaseId,'请选择合同下非押金账单');const deposit=get(s.bills,c.depositId,'押金账单');check(deposit.category==='deposit'&&deposit.leaseId===b.leaseId&&deposit.side===b.side,'押金必须来自同一份合同');check(amount<=billTotals(s,deposit.id).balance&&amount<=totals.remaining,'抵扣超过押金余额或账单欠款');depositId=deposit.id;}const e:Entry={id:uid(),kind,billId:b.id,depositId,amount,date:d,method:kind==='apply'?'押金抵扣':text(c.method??'其他','收付方式',true,80),note:text(c.note??'','备注'),reversalOf:'',createdAt:at};s.entries.push(e);audit=({payment:'登记收付款',refund:'登记退款',apply:'押金抵扣'})[kind]+'：'+b.title+' '+yuan(amount)+' 元';}
 else if(c.type==='entry.reverse'){const e=get(s.entries,c.id,'流水');check(e.kind!=='reversal','冲销记录不能再次冲销');check(!s.entries.some(x=>x.reversalOf===e.id),'此流水已冲销');const d=date(c.date);check(d>=e.date&&d<=today(),'冲销日期不得早于原流水或晚于今天');s.entries.push({...e,id:uid(),kind:'reversal',date:d,note:text(c.note,'冲销原因',true),reversalOf:e.id,createdAt:at});audit='冲销流水：'+e.id+' '+yuan(e.amount)+' 元；'+c.note;}
 else throw new Error('不支持此操作');
 check(s.properties.length<=500&&s.leases.length<=2000&&s.bills.length<=30000&&s.entries.length<=30000,'当前 MVP 容量已达上限，请导出账本');validateFinancials(s);s.audit.push({id:uid(),at,action:c.type,note:audit});s.requests.push(requestId);return s;
}
